esphome:
  name: nexxtender
  friendly_name: nexxtender

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_GATTC_NOTIF_REG_MAX: "32"  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hxorkLrui+LHteEF5DfoqVP5brcr0VtlqzzIIgII49A="

ota:
  - platform: esphome
#    password: "b2f5a1a1700cfa43a76bd87551b2098e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip: 
    static_ip: 192.168.1.230
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nexxtender Fallback Hotspot"
    password: "qhJnncr5sgYS"

captive_portal:

packages:
  nexxtender:
    url: https://github.com/geertmeersman/nexxtender
    file: config/nexxtender.yaml
    refresh: 0s

web_server:
